// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "key", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled"}, Default: "enabled"},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "profiles", Type: field.TypeJSON, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_users_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "api_keys_by_user_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[9]},
			},
			{
				Name:    "api_keys_by_key",
				Unique:  true,
				Columns: []*schema.Column{APIKeysColumns[4]},
			},
		},
	}
	// ChannelsColumns holds the columns for the "channels" table.
	ChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"openai", "anthropic", "anthropic_aws", "anthropic_gcp", "deepseek", "deepseek_anthropic", "doubao", "moonshot", "moonshot_anthropic", "zhipu", "zai", "zhipu_anthropic", "zai_anthropic", "anthropic_fake", "openai_fake"}},
		{Name: "base_url", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"enabled", "disabled", "archived"}, Default: "disabled"},
		{Name: "credentials", Type: field.TypeJSON},
		{Name: "supported_models", Type: field.TypeJSON},
		{Name: "default_test_model", Type: field.TypeString},
		{Name: "settings", Type: field.TypeJSON, Nullable: true},
		{Name: "ordering_weight", Type: field.TypeInt, Default: 0},
	}
	// ChannelsTable holds the schema information for the "channels" table.
	ChannelsTable = &schema.Table{
		Name:       "channels",
		Columns:    ChannelsColumns,
		PrimaryKey: []*schema.Column{ChannelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "channels_by_name",
				Unique:  true,
				Columns: []*schema.Column{ChannelsColumns[6]},
			},
		},
	}
	// RequestsColumns holds the columns for the "requests" table.
	RequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"api", "playground", "test"}, Default: "api"},
		{Name: "model_id", Type: field.TypeString},
		{Name: "format", Type: field.TypeString, Default: "openai/chat_completions"},
		{Name: "request_body", Type: field.TypeJSON},
		{Name: "response_body", Type: field.TypeJSON, Nullable: true},
		{Name: "response_chunks", Type: field.TypeJSON, Nullable: true},
		{Name: "external_id", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "processing", "completed", "failed"}},
		{Name: "api_key_id", Type: field.TypeInt, Nullable: true},
		{Name: "channel_id", Type: field.TypeInt, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
	}
	// RequestsTable holds the schema information for the "requests" table.
	RequestsTable = &schema.Table{
		Name:       "requests",
		Columns:    RequestsColumns,
		PrimaryKey: []*schema.Column{RequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "requests_api_keys_requests",
				Columns:    []*schema.Column{RequestsColumns[12]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "requests_channels_requests",
				Columns:    []*schema.Column{RequestsColumns[13]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "requests_users_requests",
				Columns:    []*schema.Column{RequestsColumns[14]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "requests_by_user_id",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[14]},
			},
			{
				Name:    "requests_by_api_key_id",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[12]},
			},
			{
				Name:    "requests_by_channel_id",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[13]},
			},
			{
				Name:    "requests_by_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[1]},
			},
			{
				Name:    "requests_by_status",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[11]},
			},
		},
	}
	// RequestExecutionsColumns holds the columns for the "request_executions" table.
	RequestExecutionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "external_id", Type: field.TypeString, Nullable: true},
		{Name: "model_id", Type: field.TypeString},
		{Name: "format", Type: field.TypeString, Default: "openai/chat_completions"},
		{Name: "request_body", Type: field.TypeJSON},
		{Name: "response_body", Type: field.TypeJSON, Nullable: true},
		{Name: "response_chunks", Type: field.TypeJSON, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "processing", "completed", "failed"}},
		{Name: "channel_id", Type: field.TypeInt},
		{Name: "request_id", Type: field.TypeInt},
	}
	// RequestExecutionsTable holds the schema information for the "request_executions" table.
	RequestExecutionsTable = &schema.Table{
		Name:       "request_executions",
		Columns:    RequestExecutionsColumns,
		PrimaryKey: []*schema.Column{RequestExecutionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "request_executions_channels_executions",
				Columns:    []*schema.Column{RequestExecutionsColumns[12]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "request_executions_requests_executions",
				Columns:    []*schema.Column{RequestExecutionsColumns[13]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "request_executions_by_request_id",
				Unique:  false,
				Columns: []*schema.Column{RequestExecutionsColumns[13]},
			},
			{
				Name:    "request_executions_by_channel_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestExecutionsColumns[12]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "roles_by_code",
				Unique:  true,
				Columns: []*schema.Column{RolesColumns[4]},
			},
		},
	}
	// UsageLogsColumns holds the columns for the "usage_logs" table.
	UsageLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "channel_usage_logs", Type: field.TypeInt, Nullable: true},
		{Name: "request_usage_logs", Type: field.TypeInt, Nullable: true},
		{Name: "user_usage_logs", Type: field.TypeInt, Nullable: true},
	}
	// UsageLogsTable holds the schema information for the "usage_logs" table.
	UsageLogsTable = &schema.Table{
		Name:       "usage_logs",
		Columns:    UsageLogsColumns,
		PrimaryKey: []*schema.Column{UsageLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "usage_logs_channels_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[1]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "usage_logs_requests_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[2]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "usage_logs_users_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeInt, Default: 0},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"activated", "deactivated"}, Default: "activated"},
		{Name: "prefer_language", Type: field.TypeString, Default: "en"},
		{Name: "password", Type: field.TypeString},
		{Name: "first_name", Type: field.TypeString, Default: ""},
		{Name: "last_name", Type: field.TypeString, Default: ""},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
		{Name: "is_owner", Type: field.TypeBool, Default: false},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserRolesColumns holds the columns for the "user_roles" table.
	UserRolesColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "role_id", Type: field.TypeInt},
	}
	// UserRolesTable holds the schema information for the "user_roles" table.
	UserRolesTable = &schema.Table{
		Name:       "user_roles",
		Columns:    UserRolesColumns,
		PrimaryKey: []*schema.Column{UserRolesColumns[0], UserRolesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_roles_user_id",
				Columns:    []*schema.Column{UserRolesColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_roles_role_id",
				Columns:    []*schema.Column{UserRolesColumns[1]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		ChannelsTable,
		RequestsTable,
		RequestExecutionsTable,
		RolesTable,
		UsageLogsTable,
		UsersTable,
		UserRolesTable,
	}
)

func init() {
	APIKeysTable.ForeignKeys[0].RefTable = UsersTable
	RequestsTable.ForeignKeys[0].RefTable = APIKeysTable
	RequestsTable.ForeignKeys[1].RefTable = ChannelsTable
	RequestsTable.ForeignKeys[2].RefTable = UsersTable
	RequestExecutionsTable.ForeignKeys[0].RefTable = ChannelsTable
	RequestExecutionsTable.ForeignKeys[1].RefTable = RequestsTable
	UsageLogsTable.ForeignKeys[0].RefTable = ChannelsTable
	UsageLogsTable.ForeignKeys[1].RefTable = RequestsTable
	UsageLogsTable.ForeignKeys[2].RefTable = UsersTable
	UserRolesTable.ForeignKeys[0].RefTable = UsersTable
	UserRolesTable.ForeignKeys[1].RefTable = RolesTable
}
