// Code generated by ent, DO NOT EDIT.

package usagelog

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usagelog type in the database.
	Label = "usage_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the usagelog in the database.
	Table = "usage_logs"
)

// Columns holds all SQL columns for usagelog fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "usage_logs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"channel_usage_logs",
	"request_usage_logs",
	"user_usage_logs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the UsageLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}
