// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xiajignge/aihub/internal/ent/channel"
	"github.com/xiajignge/aihub/internal/ent/request"
	"github.com/xiajignge/aihub/internal/ent/requestexecution"
	"github.com/xiajignge/aihub/internal/ent/usagelog"
	"github.com/xiajignge/aihub/internal/objects"
)

// ChannelCreate is the builder for creating a Channel entity.
type ChannelCreate struct {
	config
	mutation *ChannelMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelCreate) SetCreatedAt(v time.Time) *ChannelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableCreatedAt(v *time.Time) *ChannelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChannelCreate) SetUpdatedAt(v time.Time) *ChannelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableUpdatedAt(v *time.Time) *ChannelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ChannelCreate) SetDeletedAt(v int) *ChannelCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableDeletedAt(v *int) *ChannelCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *ChannelCreate) SetType(v channel.Type) *ChannelCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *ChannelCreate) SetBaseURL(v string) *ChannelCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableBaseURL(v *string) *ChannelCreate {
	if v != nil {
		_c.SetBaseURL(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ChannelCreate) SetName(v string) *ChannelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ChannelCreate) SetStatus(v channel.Status) *ChannelCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableStatus(v *channel.Status) *ChannelCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCredentials sets the "credentials" field.
func (_c *ChannelCreate) SetCredentials(v *objects.ChannelCredentials) *ChannelCreate {
	_c.mutation.SetCredentials(v)
	return _c
}

// SetSupportedModels sets the "supported_models" field.
func (_c *ChannelCreate) SetSupportedModels(v []string) *ChannelCreate {
	_c.mutation.SetSupportedModels(v)
	return _c
}

// SetDefaultTestModel sets the "default_test_model" field.
func (_c *ChannelCreate) SetDefaultTestModel(v string) *ChannelCreate {
	_c.mutation.SetDefaultTestModel(v)
	return _c
}

// SetSettings sets the "settings" field.
func (_c *ChannelCreate) SetSettings(v *objects.ChannelSettings) *ChannelCreate {
	_c.mutation.SetSettings(v)
	return _c
}

// SetOrderingWeight sets the "ordering_weight" field.
func (_c *ChannelCreate) SetOrderingWeight(v int) *ChannelCreate {
	_c.mutation.SetOrderingWeight(v)
	return _c
}

// SetNillableOrderingWeight sets the "ordering_weight" field if the given value is not nil.
func (_c *ChannelCreate) SetNillableOrderingWeight(v *int) *ChannelCreate {
	if v != nil {
		_c.SetOrderingWeight(*v)
	}
	return _c
}

// AddRequestIDs adds the "requests" edge to the Request entity by IDs.
func (_c *ChannelCreate) AddRequestIDs(ids ...int) *ChannelCreate {
	_c.mutation.AddRequestIDs(ids...)
	return _c
}

// AddRequests adds the "requests" edges to the Request entity.
func (_c *ChannelCreate) AddRequests(v ...*Request) *ChannelCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRequestIDs(ids...)
}

// AddExecutionIDs adds the "executions" edge to the RequestExecution entity by IDs.
func (_c *ChannelCreate) AddExecutionIDs(ids ...int) *ChannelCreate {
	_c.mutation.AddExecutionIDs(ids...)
	return _c
}

// AddExecutions adds the "executions" edges to the RequestExecution entity.
func (_c *ChannelCreate) AddExecutions(v ...*RequestExecution) *ChannelCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddExecutionIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_c *ChannelCreate) AddUsageLogIDs(ids ...int) *ChannelCreate {
	_c.mutation.AddUsageLogIDs(ids...)
	return _c
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_c *ChannelCreate) AddUsageLogs(v ...*UsageLog) *ChannelCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageLogIDs(ids...)
}

// Mutation returns the ChannelMutation object of the builder.
func (_c *ChannelCreate) Mutation() *ChannelMutation {
	return _c.mutation
}

// Save creates the Channel in the database.
func (_c *ChannelCreate) Save(ctx context.Context) (*Channel, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelCreate) SaveX(ctx context.Context) *Channel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if channel.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized channel.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := channel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if channel.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channel.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := channel.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := channel.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Credentials(); !ok {
		v := channel.DefaultCredentials
		_c.mutation.SetCredentials(v)
	}
	if _, ok := _c.mutation.Settings(); !ok {
		v := channel.DefaultSettings
		_c.mutation.SetSettings(v)
	}
	if _, ok := _c.mutation.OrderingWeight(); !ok {
		v := channel.DefaultOrderingWeight
		_c.mutation.SetOrderingWeight(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Channel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Channel.updated_at"`)}
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "Channel.deleted_at"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Channel.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := channel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Channel.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Channel.name"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Channel.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := channel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Channel.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Credentials(); !ok {
		return &ValidationError{Name: "credentials", err: errors.New(`ent: missing required field "Channel.credentials"`)}
	}
	if _, ok := _c.mutation.SupportedModels(); !ok {
		return &ValidationError{Name: "supported_models", err: errors.New(`ent: missing required field "Channel.supported_models"`)}
	}
	if _, ok := _c.mutation.DefaultTestModel(); !ok {
		return &ValidationError{Name: "default_test_model", err: errors.New(`ent: missing required field "Channel.default_test_model"`)}
	}
	if _, ok := _c.mutation.OrderingWeight(); !ok {
		return &ValidationError{Name: "ordering_weight", err: errors.New(`ent: missing required field "Channel.ordering_weight"`)}
	}
	return nil
}

func (_c *ChannelCreate) sqlSave(ctx context.Context) (*Channel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelCreate) createSpec() (*Channel, *sqlgraph.CreateSpec) {
	var (
		_node = &Channel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channel.Table, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(channel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(channel.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(channel.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(channel.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(channel.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Credentials(); ok {
		_spec.SetField(channel.FieldCredentials, field.TypeJSON, value)
		_node.Credentials = value
	}
	if value, ok := _c.mutation.SupportedModels(); ok {
		_spec.SetField(channel.FieldSupportedModels, field.TypeJSON, value)
		_node.SupportedModels = value
	}
	if value, ok := _c.mutation.DefaultTestModel(); ok {
		_spec.SetField(channel.FieldDefaultTestModel, field.TypeString, value)
		_node.DefaultTestModel = value
	}
	if value, ok := _c.mutation.Settings(); ok {
		_spec.SetField(channel.FieldSettings, field.TypeJSON, value)
		_node.Settings = value
	}
	if value, ok := _c.mutation.OrderingWeight(); ok {
		_spec.SetField(channel.FieldOrderingWeight, field.TypeInt, value)
		_node.OrderingWeight = value
	}
	if nodes := _c.mutation.RequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.RequestsTable,
			Columns: []string{channel.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ExecutionsTable,
			Columns: []string{channel.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.UsageLogsTable,
			Columns: []string{channel.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChannelCreateBulk is the builder for creating many Channel entities in bulk.
type ChannelCreateBulk struct {
	config
	err      error
	builders []*ChannelCreate
}

// Save creates the Channel entities in the database.
func (_c *ChannelCreateBulk) Save(ctx context.Context) ([]*Channel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Channel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelCreateBulk) SaveX(ctx context.Context) []*Channel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
