// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/xiajignge/aihub/internal/ent/channel"
	"github.com/xiajignge/aihub/internal/ent/predicate"
	"github.com/xiajignge/aihub/internal/ent/request"
	"github.com/xiajignge/aihub/internal/ent/requestexecution"
	"github.com/xiajignge/aihub/internal/ent/usagelog"
	"github.com/xiajignge/aihub/internal/objects"
)

// ChannelUpdate is the builder for updating Channel entities.
type ChannelUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelMutation
}

// Where appends a list predicates to the ChannelUpdate builder.
func (_u *ChannelUpdate) Where(ps ...predicate.Channel) *ChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelUpdate) SetUpdatedAt(v time.Time) *ChannelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChannelUpdate) SetDeletedAt(v int) *ChannelUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableDeletedAt(v *int) *ChannelUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ChannelUpdate) AddDeletedAt(v int) *ChannelUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *ChannelUpdate) SetBaseURL(v string) *ChannelUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableBaseURL(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// ClearBaseURL clears the value of the "base_url" field.
func (_u *ChannelUpdate) ClearBaseURL() *ChannelUpdate {
	_u.mutation.ClearBaseURL()
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelUpdate) SetName(v string) *ChannelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableName(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChannelUpdate) SetStatus(v channel.Status) *ChannelUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableStatus(v *channel.Status) *ChannelUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCredentials sets the "credentials" field.
func (_u *ChannelUpdate) SetCredentials(v *objects.ChannelCredentials) *ChannelUpdate {
	_u.mutation.SetCredentials(v)
	return _u
}

// SetSupportedModels sets the "supported_models" field.
func (_u *ChannelUpdate) SetSupportedModels(v []string) *ChannelUpdate {
	_u.mutation.SetSupportedModels(v)
	return _u
}

// AppendSupportedModels appends value to the "supported_models" field.
func (_u *ChannelUpdate) AppendSupportedModels(v []string) *ChannelUpdate {
	_u.mutation.AppendSupportedModels(v)
	return _u
}

// SetDefaultTestModel sets the "default_test_model" field.
func (_u *ChannelUpdate) SetDefaultTestModel(v string) *ChannelUpdate {
	_u.mutation.SetDefaultTestModel(v)
	return _u
}

// SetNillableDefaultTestModel sets the "default_test_model" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableDefaultTestModel(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetDefaultTestModel(*v)
	}
	return _u
}

// SetSettings sets the "settings" field.
func (_u *ChannelUpdate) SetSettings(v *objects.ChannelSettings) *ChannelUpdate {
	_u.mutation.SetSettings(v)
	return _u
}

// ClearSettings clears the value of the "settings" field.
func (_u *ChannelUpdate) ClearSettings() *ChannelUpdate {
	_u.mutation.ClearSettings()
	return _u
}

// SetOrderingWeight sets the "ordering_weight" field.
func (_u *ChannelUpdate) SetOrderingWeight(v int) *ChannelUpdate {
	_u.mutation.ResetOrderingWeight()
	_u.mutation.SetOrderingWeight(v)
	return _u
}

// SetNillableOrderingWeight sets the "ordering_weight" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableOrderingWeight(v *int) *ChannelUpdate {
	if v != nil {
		_u.SetOrderingWeight(*v)
	}
	return _u
}

// AddOrderingWeight adds value to the "ordering_weight" field.
func (_u *ChannelUpdate) AddOrderingWeight(v int) *ChannelUpdate {
	_u.mutation.AddOrderingWeight(v)
	return _u
}

// AddRequestIDs adds the "requests" edge to the Request entity by IDs.
func (_u *ChannelUpdate) AddRequestIDs(ids ...int) *ChannelUpdate {
	_u.mutation.AddRequestIDs(ids...)
	return _u
}

// AddRequests adds the "requests" edges to the Request entity.
func (_u *ChannelUpdate) AddRequests(v ...*Request) *ChannelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestIDs(ids...)
}

// AddExecutionIDs adds the "executions" edge to the RequestExecution entity by IDs.
func (_u *ChannelUpdate) AddExecutionIDs(ids ...int) *ChannelUpdate {
	_u.mutation.AddExecutionIDs(ids...)
	return _u
}

// AddExecutions adds the "executions" edges to the RequestExecution entity.
func (_u *ChannelUpdate) AddExecutions(v ...*RequestExecution) *ChannelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExecutionIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *ChannelUpdate) AddUsageLogIDs(ids ...int) *ChannelUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *ChannelUpdate) AddUsageLogs(v ...*UsageLog) *ChannelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the ChannelMutation object of the builder.
func (_u *ChannelUpdate) Mutation() *ChannelMutation {
	return _u.mutation
}

// ClearRequests clears all "requests" edges to the Request entity.
func (_u *ChannelUpdate) ClearRequests() *ChannelUpdate {
	_u.mutation.ClearRequests()
	return _u
}

// RemoveRequestIDs removes the "requests" edge to Request entities by IDs.
func (_u *ChannelUpdate) RemoveRequestIDs(ids ...int) *ChannelUpdate {
	_u.mutation.RemoveRequestIDs(ids...)
	return _u
}

// RemoveRequests removes "requests" edges to Request entities.
func (_u *ChannelUpdate) RemoveRequests(v ...*Request) *ChannelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestIDs(ids...)
}

// ClearExecutions clears all "executions" edges to the RequestExecution entity.
func (_u *ChannelUpdate) ClearExecutions() *ChannelUpdate {
	_u.mutation.ClearExecutions()
	return _u
}

// RemoveExecutionIDs removes the "executions" edge to RequestExecution entities by IDs.
func (_u *ChannelUpdate) RemoveExecutionIDs(ids ...int) *ChannelUpdate {
	_u.mutation.RemoveExecutionIDs(ids...)
	return _u
}

// RemoveExecutions removes "executions" edges to RequestExecution entities.
func (_u *ChannelUpdate) RemoveExecutions(v ...*RequestExecution) *ChannelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExecutionIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *ChannelUpdate) ClearUsageLogs() *ChannelUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *ChannelUpdate) RemoveUsageLogIDs(ids ...int) *ChannelUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *ChannelUpdate) RemoveUsageLogs(v ...*UsageLog) *ChannelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if channel.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channel.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := channel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Channel.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(channel.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(channel.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(channel.FieldBaseURL, field.TypeString, value)
	}
	if _u.mutation.BaseURLCleared() {
		_spec.ClearField(channel.FieldBaseURL, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(channel.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Credentials(); ok {
		_spec.SetField(channel.FieldCredentials, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SupportedModels(); ok {
		_spec.SetField(channel.FieldSupportedModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSupportedModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, channel.FieldSupportedModels, value)
		})
	}
	if value, ok := _u.mutation.DefaultTestModel(); ok {
		_spec.SetField(channel.FieldDefaultTestModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Settings(); ok {
		_spec.SetField(channel.FieldSettings, field.TypeJSON, value)
	}
	if _u.mutation.SettingsCleared() {
		_spec.ClearField(channel.FieldSettings, field.TypeJSON)
	}
	if value, ok := _u.mutation.OrderingWeight(); ok {
		_spec.SetField(channel.FieldOrderingWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderingWeight(); ok {
		_spec.AddField(channel.FieldOrderingWeight, field.TypeInt, value)
	}
	if _u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.RequestsTable,
			Columns: []string{channel.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestsIDs(); len(nodes) > 0 && !_u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.RequestsTable,
			Columns: []string{channel.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.RequestsTable,
			Columns: []string{channel.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ExecutionsTable,
			Columns: []string{channel.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExecutionsIDs(); len(nodes) > 0 && !_u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ExecutionsTable,
			Columns: []string{channel.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ExecutionsTable,
			Columns: []string{channel.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.UsageLogsTable,
			Columns: []string{channel.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.UsageLogsTable,
			Columns: []string{channel.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.UsageLogsTable,
			Columns: []string{channel.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelUpdateOne is the builder for updating a single Channel entity.
type ChannelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelUpdateOne) SetUpdatedAt(v time.Time) *ChannelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChannelUpdateOne) SetDeletedAt(v int) *ChannelUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableDeletedAt(v *int) *ChannelUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ChannelUpdateOne) AddDeletedAt(v int) *ChannelUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *ChannelUpdateOne) SetBaseURL(v string) *ChannelUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableBaseURL(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// ClearBaseURL clears the value of the "base_url" field.
func (_u *ChannelUpdateOne) ClearBaseURL() *ChannelUpdateOne {
	_u.mutation.ClearBaseURL()
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelUpdateOne) SetName(v string) *ChannelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableName(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChannelUpdateOne) SetStatus(v channel.Status) *ChannelUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableStatus(v *channel.Status) *ChannelUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCredentials sets the "credentials" field.
func (_u *ChannelUpdateOne) SetCredentials(v *objects.ChannelCredentials) *ChannelUpdateOne {
	_u.mutation.SetCredentials(v)
	return _u
}

// SetSupportedModels sets the "supported_models" field.
func (_u *ChannelUpdateOne) SetSupportedModels(v []string) *ChannelUpdateOne {
	_u.mutation.SetSupportedModels(v)
	return _u
}

// AppendSupportedModels appends value to the "supported_models" field.
func (_u *ChannelUpdateOne) AppendSupportedModels(v []string) *ChannelUpdateOne {
	_u.mutation.AppendSupportedModels(v)
	return _u
}

// SetDefaultTestModel sets the "default_test_model" field.
func (_u *ChannelUpdateOne) SetDefaultTestModel(v string) *ChannelUpdateOne {
	_u.mutation.SetDefaultTestModel(v)
	return _u
}

// SetNillableDefaultTestModel sets the "default_test_model" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableDefaultTestModel(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetDefaultTestModel(*v)
	}
	return _u
}

// SetSettings sets the "settings" field.
func (_u *ChannelUpdateOne) SetSettings(v *objects.ChannelSettings) *ChannelUpdateOne {
	_u.mutation.SetSettings(v)
	return _u
}

// ClearSettings clears the value of the "settings" field.
func (_u *ChannelUpdateOne) ClearSettings() *ChannelUpdateOne {
	_u.mutation.ClearSettings()
	return _u
}

// SetOrderingWeight sets the "ordering_weight" field.
func (_u *ChannelUpdateOne) SetOrderingWeight(v int) *ChannelUpdateOne {
	_u.mutation.ResetOrderingWeight()
	_u.mutation.SetOrderingWeight(v)
	return _u
}

// SetNillableOrderingWeight sets the "ordering_weight" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableOrderingWeight(v *int) *ChannelUpdateOne {
	if v != nil {
		_u.SetOrderingWeight(*v)
	}
	return _u
}

// AddOrderingWeight adds value to the "ordering_weight" field.
func (_u *ChannelUpdateOne) AddOrderingWeight(v int) *ChannelUpdateOne {
	_u.mutation.AddOrderingWeight(v)
	return _u
}

// AddRequestIDs adds the "requests" edge to the Request entity by IDs.
func (_u *ChannelUpdateOne) AddRequestIDs(ids ...int) *ChannelUpdateOne {
	_u.mutation.AddRequestIDs(ids...)
	return _u
}

// AddRequests adds the "requests" edges to the Request entity.
func (_u *ChannelUpdateOne) AddRequests(v ...*Request) *ChannelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestIDs(ids...)
}

// AddExecutionIDs adds the "executions" edge to the RequestExecution entity by IDs.
func (_u *ChannelUpdateOne) AddExecutionIDs(ids ...int) *ChannelUpdateOne {
	_u.mutation.AddExecutionIDs(ids...)
	return _u
}

// AddExecutions adds the "executions" edges to the RequestExecution entity.
func (_u *ChannelUpdateOne) AddExecutions(v ...*RequestExecution) *ChannelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExecutionIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *ChannelUpdateOne) AddUsageLogIDs(ids ...int) *ChannelUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *ChannelUpdateOne) AddUsageLogs(v ...*UsageLog) *ChannelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the ChannelMutation object of the builder.
func (_u *ChannelUpdateOne) Mutation() *ChannelMutation {
	return _u.mutation
}

// ClearRequests clears all "requests" edges to the Request entity.
func (_u *ChannelUpdateOne) ClearRequests() *ChannelUpdateOne {
	_u.mutation.ClearRequests()
	return _u
}

// RemoveRequestIDs removes the "requests" edge to Request entities by IDs.
func (_u *ChannelUpdateOne) RemoveRequestIDs(ids ...int) *ChannelUpdateOne {
	_u.mutation.RemoveRequestIDs(ids...)
	return _u
}

// RemoveRequests removes "requests" edges to Request entities.
func (_u *ChannelUpdateOne) RemoveRequests(v ...*Request) *ChannelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestIDs(ids...)
}

// ClearExecutions clears all "executions" edges to the RequestExecution entity.
func (_u *ChannelUpdateOne) ClearExecutions() *ChannelUpdateOne {
	_u.mutation.ClearExecutions()
	return _u
}

// RemoveExecutionIDs removes the "executions" edge to RequestExecution entities by IDs.
func (_u *ChannelUpdateOne) RemoveExecutionIDs(ids ...int) *ChannelUpdateOne {
	_u.mutation.RemoveExecutionIDs(ids...)
	return _u
}

// RemoveExecutions removes "executions" edges to RequestExecution entities.
func (_u *ChannelUpdateOne) RemoveExecutions(v ...*RequestExecution) *ChannelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExecutionIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *ChannelUpdateOne) ClearUsageLogs() *ChannelUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *ChannelUpdateOne) RemoveUsageLogIDs(ids ...int) *ChannelUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *ChannelUpdateOne) RemoveUsageLogs(v ...*UsageLog) *ChannelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Where appends a list predicates to the ChannelUpdate builder.
func (_u *ChannelUpdateOne) Where(ps ...predicate.Channel) *ChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelUpdateOne) Select(field string, fields ...string) *ChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Channel entity.
func (_u *ChannelUpdateOne) Save(ctx context.Context) (*Channel, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelUpdateOne) SaveX(ctx context.Context) *Channel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if channel.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channel.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := channel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Channel.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ChannelUpdateOne) sqlSave(ctx context.Context) (_node *Channel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Channel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channel.FieldID)
		for _, f := range fields {
			if !channel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(channel.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(channel.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(channel.FieldBaseURL, field.TypeString, value)
	}
	if _u.mutation.BaseURLCleared() {
		_spec.ClearField(channel.FieldBaseURL, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(channel.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Credentials(); ok {
		_spec.SetField(channel.FieldCredentials, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SupportedModels(); ok {
		_spec.SetField(channel.FieldSupportedModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSupportedModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, channel.FieldSupportedModels, value)
		})
	}
	if value, ok := _u.mutation.DefaultTestModel(); ok {
		_spec.SetField(channel.FieldDefaultTestModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Settings(); ok {
		_spec.SetField(channel.FieldSettings, field.TypeJSON, value)
	}
	if _u.mutation.SettingsCleared() {
		_spec.ClearField(channel.FieldSettings, field.TypeJSON)
	}
	if value, ok := _u.mutation.OrderingWeight(); ok {
		_spec.SetField(channel.FieldOrderingWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderingWeight(); ok {
		_spec.AddField(channel.FieldOrderingWeight, field.TypeInt, value)
	}
	if _u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.RequestsTable,
			Columns: []string{channel.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestsIDs(); len(nodes) > 0 && !_u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.RequestsTable,
			Columns: []string{channel.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.RequestsTable,
			Columns: []string{channel.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ExecutionsTable,
			Columns: []string{channel.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExecutionsIDs(); len(nodes) > 0 && !_u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ExecutionsTable,
			Columns: []string{channel.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ExecutionsTable,
			Columns: []string{channel.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.UsageLogsTable,
			Columns: []string{channel.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.UsageLogsTable,
			Columns: []string{channel.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.UsageLogsTable,
			Columns: []string{channel.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Channel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
