// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xiajignge/aihub/internal/ent/apikey"
	"github.com/xiajignge/aihub/internal/ent/channel"
	"github.com/xiajignge/aihub/internal/ent/request"
	"github.com/xiajignge/aihub/internal/ent/requestexecution"
	"github.com/xiajignge/aihub/internal/ent/usagelog"
	"github.com/xiajignge/aihub/internal/ent/user"
	"github.com/xiajignge/aihub/internal/objects"
)

// RequestCreate is the builder for creating a Request entity.
type RequestCreate struct {
	config
	mutation *RequestMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestCreate) SetCreatedAt(v time.Time) *RequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequestCreate) SetNillableCreatedAt(v *time.Time) *RequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RequestCreate) SetUpdatedAt(v time.Time) *RequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RequestCreate) SetNillableUpdatedAt(v *time.Time) *RequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *RequestCreate) SetDeletedAt(v int) *RequestCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *RequestCreate) SetNillableDeletedAt(v *int) *RequestCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RequestCreate) SetUserID(v int) *RequestCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *RequestCreate) SetAPIKeyID(v int) *RequestCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *RequestCreate) SetNillableAPIKeyID(v *int) *RequestCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *RequestCreate) SetSource(v request.Source) *RequestCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *RequestCreate) SetNillableSource(v *request.Source) *RequestCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *RequestCreate) SetModelID(v string) *RequestCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetFormat sets the "format" field.
func (_c *RequestCreate) SetFormat(v string) *RequestCreate {
	_c.mutation.SetFormat(v)
	return _c
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_c *RequestCreate) SetNillableFormat(v *string) *RequestCreate {
	if v != nil {
		_c.SetFormat(*v)
	}
	return _c
}

// SetRequestBody sets the "request_body" field.
func (_c *RequestCreate) SetRequestBody(v objects.JSONRawMessage) *RequestCreate {
	_c.mutation.SetRequestBody(v)
	return _c
}

// SetResponseBody sets the "response_body" field.
func (_c *RequestCreate) SetResponseBody(v objects.JSONRawMessage) *RequestCreate {
	_c.mutation.SetResponseBody(v)
	return _c
}

// SetResponseChunks sets the "response_chunks" field.
func (_c *RequestCreate) SetResponseChunks(v []objects.JSONRawMessage) *RequestCreate {
	_c.mutation.SetResponseChunks(v)
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *RequestCreate) SetChannelID(v int) *RequestCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_c *RequestCreate) SetNillableChannelID(v *int) *RequestCreate {
	if v != nil {
		_c.SetChannelID(*v)
	}
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *RequestCreate) SetExternalID(v string) *RequestCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_c *RequestCreate) SetNillableExternalID(v *string) *RequestCreate {
	if v != nil {
		_c.SetExternalID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RequestCreate) SetStatus(v request.Status) *RequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *RequestCreate) SetUser(v *User) *RequestCreate {
	return _c.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *RequestCreate) SetAPIKey(v *APIKey) *RequestCreate {
	return _c.SetAPIKeyID(v.ID)
}

// AddExecutionIDs adds the "executions" edge to the RequestExecution entity by IDs.
func (_c *RequestCreate) AddExecutionIDs(ids ...int) *RequestCreate {
	_c.mutation.AddExecutionIDs(ids...)
	return _c
}

// AddExecutions adds the "executions" edges to the RequestExecution entity.
func (_c *RequestCreate) AddExecutions(v ...*RequestExecution) *RequestCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddExecutionIDs(ids...)
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *RequestCreate) SetChannel(v *Channel) *RequestCreate {
	return _c.SetChannelID(v.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_c *RequestCreate) AddUsageLogIDs(ids ...int) *RequestCreate {
	_c.mutation.AddUsageLogIDs(ids...)
	return _c
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_c *RequestCreate) AddUsageLogs(v ...*UsageLog) *RequestCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageLogIDs(ids...)
}

// Mutation returns the RequestMutation object of the builder.
func (_c *RequestCreate) Mutation() *RequestMutation {
	return _c.mutation
}

// Save creates the Request in the database.
func (_c *RequestCreate) Save(ctx context.Context) (*Request, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestCreate) SaveX(ctx context.Context) *Request {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if request.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized request.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := request.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if request.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized request.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := request.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := request.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := request.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Format(); !ok {
		v := request.DefaultFormat
		_c.mutation.SetFormat(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Request.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Request.updated_at"`)}
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "Request.deleted_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Request.user_id"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Request.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := request.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Request.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "Request.model_id"`)}
	}
	if _, ok := _c.mutation.Format(); !ok {
		return &ValidationError{Name: "format", err: errors.New(`ent: missing required field "Request.format"`)}
	}
	if _, ok := _c.mutation.RequestBody(); !ok {
		return &ValidationError{Name: "request_body", err: errors.New(`ent: missing required field "Request.request_body"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Request.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := request.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Request.status": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Request.user"`)}
	}
	return nil
}

func (_c *RequestCreate) sqlSave(ctx context.Context) (*Request, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestCreate) createSpec() (*Request, *sqlgraph.CreateSpec) {
	var (
		_node = &Request{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(request.Table, sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(request.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(request.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(request.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(request.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(request.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.Format(); ok {
		_spec.SetField(request.FieldFormat, field.TypeString, value)
		_node.Format = value
	}
	if value, ok := _c.mutation.RequestBody(); ok {
		_spec.SetField(request.FieldRequestBody, field.TypeJSON, value)
		_node.RequestBody = value
	}
	if value, ok := _c.mutation.ResponseBody(); ok {
		_spec.SetField(request.FieldResponseBody, field.TypeJSON, value)
		_node.ResponseBody = value
	}
	if value, ok := _c.mutation.ResponseChunks(); ok {
		_spec.SetField(request.FieldResponseChunks, field.TypeJSON, value)
		_node.ResponseChunks = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(request.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(request.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.UserTable,
			Columns: []string{request.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.APIKeyTable,
			Columns: []string{request.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.ExecutionsTable,
			Columns: []string{request.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.ChannelTable,
			Columns: []string{request.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.UsageLogsTable,
			Columns: []string{request.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RequestCreateBulk is the builder for creating many Request entities in bulk.
type RequestCreateBulk struct {
	config
	err      error
	builders []*RequestCreate
}

// Save creates the Request entities in the database.
func (_c *RequestCreateBulk) Save(ctx context.Context) ([]*Request, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Request, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestCreateBulk) SaveX(ctx context.Context) []*Request {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
