// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/xiajignge/aihub/internal/ent/predicate"
	"github.com/xiajignge/aihub/internal/ent/requestexecution"
	"github.com/xiajignge/aihub/internal/objects"
)

// RequestExecutionUpdate is the builder for updating RequestExecution entities.
type RequestExecutionUpdate struct {
	config
	hooks    []Hook
	mutation *RequestExecutionMutation
}

// Where appends a list predicates to the RequestExecutionUpdate builder.
func (_u *RequestExecutionUpdate) Where(ps ...predicate.RequestExecution) *RequestExecutionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestExecutionUpdate) SetUpdatedAt(v time.Time) *RequestExecutionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *RequestExecutionUpdate) SetExternalID(v string) *RequestExecutionUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *RequestExecutionUpdate) SetNillableExternalID(v *string) *RequestExecutionUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *RequestExecutionUpdate) ClearExternalID() *RequestExecutionUpdate {
	_u.mutation.ClearExternalID()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *RequestExecutionUpdate) SetResponseBody(v objects.JSONRawMessage) *RequestExecutionUpdate {
	_u.mutation.SetResponseBody(v)
	return _u
}

// AppendResponseBody appends value to the "response_body" field.
func (_u *RequestExecutionUpdate) AppendResponseBody(v objects.JSONRawMessage) *RequestExecutionUpdate {
	_u.mutation.AppendResponseBody(v)
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *RequestExecutionUpdate) ClearResponseBody() *RequestExecutionUpdate {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetResponseChunks sets the "response_chunks" field.
func (_u *RequestExecutionUpdate) SetResponseChunks(v []objects.JSONRawMessage) *RequestExecutionUpdate {
	_u.mutation.SetResponseChunks(v)
	return _u
}

// AppendResponseChunks appends value to the "response_chunks" field.
func (_u *RequestExecutionUpdate) AppendResponseChunks(v []objects.JSONRawMessage) *RequestExecutionUpdate {
	_u.mutation.AppendResponseChunks(v)
	return _u
}

// ClearResponseChunks clears the value of the "response_chunks" field.
func (_u *RequestExecutionUpdate) ClearResponseChunks() *RequestExecutionUpdate {
	_u.mutation.ClearResponseChunks()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RequestExecutionUpdate) SetErrorMessage(v string) *RequestExecutionUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RequestExecutionUpdate) SetNillableErrorMessage(v *string) *RequestExecutionUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RequestExecutionUpdate) ClearErrorMessage() *RequestExecutionUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RequestExecutionUpdate) SetStatus(v requestexecution.Status) *RequestExecutionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RequestExecutionUpdate) SetNillableStatus(v *requestexecution.Status) *RequestExecutionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the RequestExecutionMutation object of the builder.
func (_u *RequestExecutionUpdate) Mutation() *RequestExecutionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestExecutionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestExecutionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestExecutionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestExecutionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestExecutionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := requestexecution.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestExecutionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := requestexecution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RequestExecution.status": %w`, err)}
		}
	}
	if _u.mutation.RequestCleared() && len(_u.mutation.RequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestExecution.request"`)
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestExecution.channel"`)
	}
	return nil
}

func (_u *RequestExecutionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestexecution.Table, requestexecution.Columns, sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(requestexecution.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(requestexecution.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(requestexecution.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(requestexecution.FieldResponseBody, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResponseBody(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestexecution.FieldResponseBody, value)
		})
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(requestexecution.FieldResponseBody, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResponseChunks(); ok {
		_spec.SetField(requestexecution.FieldResponseChunks, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResponseChunks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestexecution.FieldResponseChunks, value)
		})
	}
	if _u.mutation.ResponseChunksCleared() {
		_spec.ClearField(requestexecution.FieldResponseChunks, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(requestexecution.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(requestexecution.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(requestexecution.FieldStatus, field.TypeEnum, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestexecution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestExecutionUpdateOne is the builder for updating a single RequestExecution entity.
type RequestExecutionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestExecutionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestExecutionUpdateOne) SetUpdatedAt(v time.Time) *RequestExecutionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *RequestExecutionUpdateOne) SetExternalID(v string) *RequestExecutionUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *RequestExecutionUpdateOne) SetNillableExternalID(v *string) *RequestExecutionUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *RequestExecutionUpdateOne) ClearExternalID() *RequestExecutionUpdateOne {
	_u.mutation.ClearExternalID()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *RequestExecutionUpdateOne) SetResponseBody(v objects.JSONRawMessage) *RequestExecutionUpdateOne {
	_u.mutation.SetResponseBody(v)
	return _u
}

// AppendResponseBody appends value to the "response_body" field.
func (_u *RequestExecutionUpdateOne) AppendResponseBody(v objects.JSONRawMessage) *RequestExecutionUpdateOne {
	_u.mutation.AppendResponseBody(v)
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *RequestExecutionUpdateOne) ClearResponseBody() *RequestExecutionUpdateOne {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetResponseChunks sets the "response_chunks" field.
func (_u *RequestExecutionUpdateOne) SetResponseChunks(v []objects.JSONRawMessage) *RequestExecutionUpdateOne {
	_u.mutation.SetResponseChunks(v)
	return _u
}

// AppendResponseChunks appends value to the "response_chunks" field.
func (_u *RequestExecutionUpdateOne) AppendResponseChunks(v []objects.JSONRawMessage) *RequestExecutionUpdateOne {
	_u.mutation.AppendResponseChunks(v)
	return _u
}

// ClearResponseChunks clears the value of the "response_chunks" field.
func (_u *RequestExecutionUpdateOne) ClearResponseChunks() *RequestExecutionUpdateOne {
	_u.mutation.ClearResponseChunks()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RequestExecutionUpdateOne) SetErrorMessage(v string) *RequestExecutionUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RequestExecutionUpdateOne) SetNillableErrorMessage(v *string) *RequestExecutionUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RequestExecutionUpdateOne) ClearErrorMessage() *RequestExecutionUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RequestExecutionUpdateOne) SetStatus(v requestexecution.Status) *RequestExecutionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RequestExecutionUpdateOne) SetNillableStatus(v *requestexecution.Status) *RequestExecutionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the RequestExecutionMutation object of the builder.
func (_u *RequestExecutionUpdateOne) Mutation() *RequestExecutionMutation {
	return _u.mutation
}

// Where appends a list predicates to the RequestExecutionUpdate builder.
func (_u *RequestExecutionUpdateOne) Where(ps ...predicate.RequestExecution) *RequestExecutionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestExecutionUpdateOne) Select(field string, fields ...string) *RequestExecutionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestExecution entity.
func (_u *RequestExecutionUpdateOne) Save(ctx context.Context) (*RequestExecution, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestExecutionUpdateOne) SaveX(ctx context.Context) *RequestExecution {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestExecutionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestExecutionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestExecutionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := requestexecution.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestExecutionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := requestexecution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RequestExecution.status": %w`, err)}
		}
	}
	if _u.mutation.RequestCleared() && len(_u.mutation.RequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestExecution.request"`)
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestExecution.channel"`)
	}
	return nil
}

func (_u *RequestExecutionUpdateOne) sqlSave(ctx context.Context) (_node *RequestExecution, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestexecution.Table, requestexecution.Columns, sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestExecution.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestexecution.FieldID)
		for _, f := range fields {
			if !requestexecution.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestexecution.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(requestexecution.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(requestexecution.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(requestexecution.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(requestexecution.FieldResponseBody, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResponseBody(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestexecution.FieldResponseBody, value)
		})
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(requestexecution.FieldResponseBody, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResponseChunks(); ok {
		_spec.SetField(requestexecution.FieldResponseChunks, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResponseChunks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestexecution.FieldResponseChunks, value)
		})
	}
	if _u.mutation.ResponseChunksCleared() {
		_spec.ClearField(requestexecution.FieldResponseChunks, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(requestexecution.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(requestexecution.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(requestexecution.FieldStatus, field.TypeEnum, value)
	}
	_node = &RequestExecution{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestexecution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
