// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xiajignge/aihub/internal/ent/channel"
	"github.com/xiajignge/aihub/internal/ent/request"
	"github.com/xiajignge/aihub/internal/ent/requestexecution"
	"github.com/xiajignge/aihub/internal/objects"
)

// RequestExecutionCreate is the builder for creating a RequestExecution entity.
type RequestExecutionCreate struct {
	config
	mutation *RequestExecutionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestExecutionCreate) SetCreatedAt(v time.Time) *RequestExecutionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequestExecutionCreate) SetNillableCreatedAt(v *time.Time) *RequestExecutionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RequestExecutionCreate) SetUpdatedAt(v time.Time) *RequestExecutionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RequestExecutionCreate) SetNillableUpdatedAt(v *time.Time) *RequestExecutionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RequestExecutionCreate) SetUserID(v int) *RequestExecutionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *RequestExecutionCreate) SetRequestID(v int) *RequestExecutionCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *RequestExecutionCreate) SetChannelID(v int) *RequestExecutionCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *RequestExecutionCreate) SetExternalID(v string) *RequestExecutionCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_c *RequestExecutionCreate) SetNillableExternalID(v *string) *RequestExecutionCreate {
	if v != nil {
		_c.SetExternalID(*v)
	}
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *RequestExecutionCreate) SetModelID(v string) *RequestExecutionCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetFormat sets the "format" field.
func (_c *RequestExecutionCreate) SetFormat(v string) *RequestExecutionCreate {
	_c.mutation.SetFormat(v)
	return _c
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_c *RequestExecutionCreate) SetNillableFormat(v *string) *RequestExecutionCreate {
	if v != nil {
		_c.SetFormat(*v)
	}
	return _c
}

// SetRequestBody sets the "request_body" field.
func (_c *RequestExecutionCreate) SetRequestBody(v objects.JSONRawMessage) *RequestExecutionCreate {
	_c.mutation.SetRequestBody(v)
	return _c
}

// SetResponseBody sets the "response_body" field.
func (_c *RequestExecutionCreate) SetResponseBody(v objects.JSONRawMessage) *RequestExecutionCreate {
	_c.mutation.SetResponseBody(v)
	return _c
}

// SetResponseChunks sets the "response_chunks" field.
func (_c *RequestExecutionCreate) SetResponseChunks(v []objects.JSONRawMessage) *RequestExecutionCreate {
	_c.mutation.SetResponseChunks(v)
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *RequestExecutionCreate) SetErrorMessage(v string) *RequestExecutionCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *RequestExecutionCreate) SetNillableErrorMessage(v *string) *RequestExecutionCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RequestExecutionCreate) SetStatus(v requestexecution.Status) *RequestExecutionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetRequest sets the "request" edge to the Request entity.
func (_c *RequestExecutionCreate) SetRequest(v *Request) *RequestExecutionCreate {
	return _c.SetRequestID(v.ID)
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *RequestExecutionCreate) SetChannel(v *Channel) *RequestExecutionCreate {
	return _c.SetChannelID(v.ID)
}

// Mutation returns the RequestExecutionMutation object of the builder.
func (_c *RequestExecutionCreate) Mutation() *RequestExecutionMutation {
	return _c.mutation
}

// Save creates the RequestExecution in the database.
func (_c *RequestExecutionCreate) Save(ctx context.Context) (*RequestExecution, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestExecutionCreate) SaveX(ctx context.Context) *RequestExecution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestExecutionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestExecutionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestExecutionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := requestexecution.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := requestexecution.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Format(); !ok {
		v := requestexecution.DefaultFormat
		_c.mutation.SetFormat(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestExecutionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RequestExecution.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RequestExecution.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RequestExecution.user_id"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "RequestExecution.request_id"`)}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "RequestExecution.channel_id"`)}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "RequestExecution.model_id"`)}
	}
	if _, ok := _c.mutation.Format(); !ok {
		return &ValidationError{Name: "format", err: errors.New(`ent: missing required field "RequestExecution.format"`)}
	}
	if _, ok := _c.mutation.RequestBody(); !ok {
		return &ValidationError{Name: "request_body", err: errors.New(`ent: missing required field "RequestExecution.request_body"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RequestExecution.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := requestexecution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RequestExecution.status": %w`, err)}
		}
	}
	if len(_c.mutation.RequestIDs()) == 0 {
		return &ValidationError{Name: "request", err: errors.New(`ent: missing required edge "RequestExecution.request"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "RequestExecution.channel"`)}
	}
	return nil
}

func (_c *RequestExecutionCreate) sqlSave(ctx context.Context) (*RequestExecution, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestExecutionCreate) createSpec() (*RequestExecution, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestExecution{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestexecution.Table, sqlgraph.NewFieldSpec(requestexecution.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(requestexecution.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(requestexecution.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(requestexecution.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(requestexecution.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(requestexecution.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.Format(); ok {
		_spec.SetField(requestexecution.FieldFormat, field.TypeString, value)
		_node.Format = value
	}
	if value, ok := _c.mutation.RequestBody(); ok {
		_spec.SetField(requestexecution.FieldRequestBody, field.TypeJSON, value)
		_node.RequestBody = value
	}
	if value, ok := _c.mutation.ResponseBody(); ok {
		_spec.SetField(requestexecution.FieldResponseBody, field.TypeJSON, value)
		_node.ResponseBody = value
	}
	if value, ok := _c.mutation.ResponseChunks(); ok {
		_spec.SetField(requestexecution.FieldResponseChunks, field.TypeJSON, value)
		_node.ResponseChunks = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(requestexecution.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(requestexecution.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.RequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestexecution.RequestTable,
			Columns: []string{requestexecution.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RequestID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestexecution.ChannelTable,
			Columns: []string{requestexecution.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RequestExecutionCreateBulk is the builder for creating many RequestExecution entities in bulk.
type RequestExecutionCreateBulk struct {
	config
	err      error
	builders []*RequestExecutionCreate
}

// Save creates the RequestExecution entities in the database.
func (_c *RequestExecutionCreateBulk) Save(ctx context.Context) ([]*RequestExecution, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestExecution, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestExecutionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestExecutionCreateBulk) SaveX(ctx context.Context) []*RequestExecution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestExecutionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestExecutionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
