// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/xiajignge/aihub/internal/ent/usagelog"
)

// UsageLog is the model entity for the UsageLog schema.
type UsageLog struct {
	config
	// ID of the ent.
	ID                 int `json:"id,omitempty"`
	channel_usage_logs *int
	request_usage_logs *int
	user_usage_logs    *int
	selectValues       sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagelog.FieldID:
			values[i] = new(sql.NullInt64)
		case usagelog.ForeignKeys[0]: // channel_usage_logs
			values[i] = new(sql.NullInt64)
		case usagelog.ForeignKeys[1]: // request_usage_logs
			values[i] = new(sql.NullInt64)
		case usagelog.ForeignKeys[2]: // user_usage_logs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageLog fields.
func (_m *UsageLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagelog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case usagelog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field channel_usage_logs", value)
			} else if value.Valid {
				_m.channel_usage_logs = new(int)
				*_m.channel_usage_logs = int(value.Int64)
			}
		case usagelog.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field request_usage_logs", value)
			} else if value.Valid {
				_m.request_usage_logs = new(int)
				*_m.request_usage_logs = int(value.Int64)
			}
		case usagelog.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_usage_logs", value)
			} else if value.Valid {
				_m.user_usage_logs = new(int)
				*_m.user_usage_logs = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageLog.
// This includes values selected through modifiers, order, etc.
func (_m *UsageLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UsageLog.
// Note that you need to call UsageLog.Unwrap() before calling this method if this UsageLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageLog) Update() *UsageLogUpdateOne {
	return NewUsageLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageLog) Unwrap() *UsageLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageLog) String() string {
	var builder strings.Builder
	builder.WriteString("UsageLog(")
	builder.WriteString(fmt.Sprintf("id=%v", _m.ID))
	builder.WriteByte(')')
	return builder.String()
}

// UsageLogs is a parsable slice of UsageLog.
type UsageLogs []*UsageLog
