// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIKey is the predicate function for apikey builders.
type APIKey func(*sql.Selector)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// Request is the predicate function for request builders.
type Request func(*sql.Selector)

// RequestExecution is the predicate function for requestexecution builders.
type RequestExecution func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// UsageLog is the predicate function for usagelog builders.
type UsageLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
